version: '3'

services:
    pbs-build:
      image: ${CONTAINER_PLATFORM}
      volumes:
        - ../:/pbssrc
        - ./:/src
        - ./logs:/logs
        - ./etc:/workspace/etc
      entrypoint: /workspace/etc/container-init "/src/docker-entrypoint"
      env_file: .env
      environment:
        - CLUSTER_INFO='SERVER:${CONTAINER_PLATFORM}'
        - NODE_TYPE='server'
      networks:
        ci:
          aliases:
            - pbs_server
      hostname: pbs.ci
      user: root
      privileged: true

networks:
  ci:
    driver: bridge
